[package]
name = "phprs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
phprs_lexer = { path = "crates/lexer" }
phprs_parser = { path = "crates/parser" }

[dependencies]
phprs_lexer.workspace = true
phprs_parser.workspace = true
