[package]
name = "phprs_lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
log.workspace = true
anyhow.workspace = true
phprs_parser.workspace = true
phprs_lexer.workspace = true
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde_json = "1.0.140"
chumsky = "0.10.0"
