[package]
name = "phprs_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.14.0"
datatest = "0.8.0"

# TODO: Put in test only
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
