[package]
name = "phprs_parserr"
version = "0.1.0"
edition = "2021"

[dependencies]
phprs_lexer.workspace = true
ariadne = "0.2"
chumsky = { version = "0.10.0", features = [
  "pratt",
  "unstable",
  "nightly",
] }
